### ISSUE TITLE
Support for MacOS 10.15

### ISSUE THREAD

**Issue by Ectalite** [TheNightmanCodeth/mission#12]
I would know if you could support MacOS 10.15 as I don't want to update to MacOS 11.
Thanks !

**Comment by TheNightmanCodeth** [comment]
Yeah it looks like I should be able to get it working with something like this:

    if #available(macOS 10.16, *) {
        MyAwesomeNewImplementaitonOfApp.main()
    } else {
        let app = NSApplication.shared
        let delegate = AppDelegate()
        app.delegate = delegate
        app.run()
    }

I don't have any way to test it out so I'll reply here when I figure it out!

**Comment by Ectalite** [comment]
I have xcode, so I can test it. 
But for the moment, it says that the version of xcode is too low to use the xcodeproject file.

**Comment by TheNightmanCodeth** [comment]
Yeah after further investigation it would require a complete rewrite. The new SwiftUI app functionality is not backwards compatible. I'm closing this issue for now but if new information comes up and someone finds a way to get it running on older versions I'll tackle the issue. Until then I won't be able to support macOS < 10.16 unfortunately
